/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tableViewer.java
 *
 * Created on May 1, 2017, 6:38:12 PM
 */
package etlg;
import com.healthmarketscience.jackcess.*;
import java.awt.EventQueue;
import javax.swing.JTable;
/**
 *
 * @author mike
 */
public class tableViewer extends javax.swing.JFrame {
    private databaseMDB database;
    private String tableName;
    private Table table;
    /** Creates new form tableViewer */
    
    public tableViewer(){
        this.database = tableChooser.getDatabaseObject();
        this.tableName = tableChooser.jComboBox1.getSelectedItem().toString();
        this.database.setGenericTable(this.tableName);
        this.table = this.database.getGenericTable();
        initComponents();
        setJackcessTable();
    }
    
    private databaseMDB getMDBdatabase(){
        return this.database;
    }
    private String getTableName(){
        return this.tableName;
    }
    public Table getTable(){
        return this.table;
    }
    
    private void setJackcessTable(){
        int i = 0;
        int j;
        int columnNumber = this.table.getColumnCount();
        int rowNumber = this.table.getRowCount();
        Object[] columnNames = new Object[columnNumber];
        String[] columnDataType = new String[columnNumber];
        Object[][] data = new Object[columnNumber][rowNumber];
        for(Column column : this.table.getColumns()){
            columnNames[i] = column.getName();
            columnDataType[i] = column.getType().toString();
            j = 0;
            for(Row row : this.table) {
                data[i][j] = row.get(columnNames[i].toString());
            }
            i++;
        }
        setJTable(data, columnNames);
    }
    
    private void setJTable(Object[][] data, Object[] columnNames){
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbOpener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbOpener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbOpener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbOpener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tableViewer().setVisible(true);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
